// frontend/angular/src/app/shared/components/layout/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [RouterModule, FormsModule, CommonModule],
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {
  currentYear: number = new Date().getFullYear();
  newsletterEmail: string = '';

  constructor() { }

  ngOnInit(): void {
  }

  subscribeNewsletter(): void {
    if (this.newsletterEmail) {
      // Aquí iría la lógica para enviar la suscripción al backend
      console.log('Suscrito con email:', this.newsletterEmail);
      alert('¡Gracias por suscribirte a nuestro boletín!');
      this.newsletterEmail = '';
    }
  }
}
<footer class="footer">
    <div class="footerMain">
      <div class="container">
        <div class="footerContent">
          <!-- Column 1: Logo and description -->
          <div class="footerBrand">
            <div class="logo">
              <img 
                src="/Logo_VitalNest.png" 
                alt="VitalNest Logo" 
                width="180" 
                height="180"
              />
            </div>
            <p class="brandText">
              Elevando los estándares del cuidado geriátrico con elegancia y dedicación. Un espacio donde el bienestar y la calidad de vida se fusionan para crear experiencias excepcionales.
            </p>
            <div class="socialIcons">
              <a href="#" class="socialIconWrapper" aria-label="Facebook">
                <i class="fab fa-facebook-f"></i>
              </a>
              <a href="#" class="socialIconWrapper" aria-label="Twitter">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#" class="socialIconWrapper" aria-label="Instagram">
                <i class="fab fa-instagram"></i>
              </a>
              <a href="#" class="socialIconWrapper" aria-label="LinkedIn">
                <i class="fab fa-linkedin-in"></i>
              </a>
              <a href="#" class="socialIconWrapper" aria-label="YouTube">
                <i class="fab fa-youtube"></i>
              </a>
            </div>
          </div>
          
          <!-- Column 2: Links -->
          <div class="footerNavigation">
            <div class="linkColumn">
              <h3>Servicios</h3>
              <ul>
                <li><a routerLink="/servicios/residencia">Residencia Premium</a></li>
                <li><a routerLink="/servicios/cuidados">Cuidados Especializados</a></li>
                <li><a routerLink="/servicios/actividades">Programa de Actividades</a></li>
                <li><a routerLink="/servicios/gastronomia">Gastronomía Saludable</a></li>
              </ul>
            </div>

            <div class="linkColumn">
              <h3>Sobre Nosotros</h3>
              <ul>
                <li><a routerLink="/sobre-nosotros">Quiénes Somos</a></li>
                <li><a routerLink="/instalaciones">Instalaciones</a></li>
                <li><a routerLink="/equipo">Equipo Profesional</a></li>
                <li><a routerLink="/blog">Blog de Salud</a></li>
              </ul>
            </div>
          </div>
          
          <!-- Column 3: Contact -->
          <div class="footerContact">
            <h3>Contacto</h3>
            <div class="contactInfo">
              <div class="contactItem">
                <i class="fa fa-phone contactIcon"></i>
                <span>900 123 456</span>
              </div>
              <div class="contactItem">
                <i class="fa fa-envelope contactIcon"></i>
                <span>info&#64;vitalnest.com</span>
              </div>
              <div class="contactItem">
                <i class="fa fa-map-marker contactIcon"></i>
                <span>Paseo de la Castellana 200, Madrid</span>
              </div>
              <div class="contactItem">
                <i class="fa fa-clock-o contactIcon"></i>
                <span>Atención 24/7</span>
              </div>
            </div>
            
            <div class="newsletterContainer">
              <h3>Boletín Informativo</h3>
              <form class="newsletterForm" (ngSubmit)="subscribeNewsletter()">
                <input type="email" placeholder="Tu correo electrónico" required />
                <button type="submit">Suscribirse</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Footer bottom -->
    <div class="footerBottom">
      <div class="container">
        <div class="bottomContent">
          <p class="copyright">© {{currentYear}} VitalNest - Todos los derechos reservados</p>
          <div class="bottomLinks">
            <a routerLink="/privacidad"><i class="fa fa-shield"></i> Política de Privacidad</a>
            <a routerLink="/terminos"><i class="fa fa-file-text"></i> Términos de Uso</a>
            <a routerLink="/cookies"><i class="fa fa-cookie-bite"></i> Política de Cookies</a>
            <a routerLink="/accesibilidad"><i class="fa fa-universal-access"></i> Accesibilidad</a>
          </div>
        </div>
      </div>
    </div>
</footer>

// fullstack/next/src/components/layout/Footer.tsx
import React from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { FaFacebookF, FaTwitter, FaInstagram, FaLinkedinIn, FaYoutube } from 'react-icons/fa';
import { MdPhone, MdEmail, MdLocationOn, MdAccessTime } from 'react-icons/md';
import styles from '../../styles/layout/Footer.module.css';

const Footer: React.FC = () => {
  const currentYear = new Date().getFullYear();
  
  return (
    <footer className={styles.footer}>
      {/* <div className={styles.footerWave}>
        <svg viewBox="0 0 1440 120" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M0,0 C320,80 520,80 720,40 C920,0 1120,0 1440,80 L1440,120 L0,120 Z" fill="currentColor"/>
        </svg>
      </div>       */}
      <div className={styles.footerMain}>
        <div className={styles.container}>
          <div className={styles.footerContent}>
            {/* Columna 1: Logo y descripción */}
            <div className={styles.footerBrand}>
              <div className={styles.logo}>
                <Image 
                  src="/Logo_VitalNest.png" 
                  alt="VitalNest Logo" 
                  width={180} 
                  height={180} 
                  priority
                />
              </div>
              <p className={styles.brandText}>
                Elevando los estándares del cuidado geriátrico con elegancia y dedicación. Un espacio donde el bienestar y la calidad de vida se fusionan para crear experiencias excepcionales.
              </p>
              <div className={styles.socialIcons}>
                <a href="#" className={styles.socialIconWrapper} aria-label="Facebook">
                  <FaFacebookF />
                </a>
                <a href="#" className={styles.socialIconWrapper} aria-label="Twitter">
                  <FaTwitter />
                </a>
                <a href="#" className={styles.socialIconWrapper} aria-label="Instagram">
                  <FaInstagram />
                </a>
                <a href="#" className={styles.socialIconWrapper} aria-label="LinkedIn">
                  <FaLinkedinIn />
                </a>
                <a href="#" className={styles.socialIconWrapper} aria-label="YouTube">
                  <FaYoutube />
                </a>
              </div>
            </div>
            
            {/* Columna 2: Enlaces */}
            <div className={styles.footerNavigation}>
              <div className={styles.linkColumn}>
                <h3>Servicios</h3>
                <ul>
                  <li><Link href="/servicios/residencia">Residencia Premium</Link></li>
                  <li><Link href="/servicios/cuidados">Cuidados Especializados</Link></li>
                  <li><Link href="/servicios/actividades">Programa de Actividades</Link></li>
                  <li><Link href="/servicios/gastronomia">Gastronomía Saludable</Link></li>
                </ul>
              </div>

              <div className={styles.linkColumn}>
                <h3>Sobre Nosotros</h3>
                <ul>
                  <li><Link href="/sobre-nosotros">Quiénes Somos</Link></li>
                  <li><Link href="/instalaciones">Instalaciones</Link></li>
                  <li><Link href="/equipo">Equipo Profesional</Link></li>
                  <li><Link href="/blog">Blog de Salud</Link></li>
                </ul>
              </div>
            </div>
            
            {/* Columna 3: Contacto */}
            <div className={styles.footerContact}>
              <h3>Contacto</h3>
              <div className={styles.contactInfo}>
                <div className={styles.contactItem}>
                  <MdPhone className={styles.contactIcon}/>
                  <span>900 123 456</span>
                </div>
                <div className={styles.contactItem}>
                  <MdEmail className={styles.contactIcon}/>
                  <span>info@vitalnest.com</span>
                </div>
                <div className={styles.contactItem}>
                  <MdLocationOn className={styles.contactIcon}/>
                  <span>Paseo de la Castellana 200, Madrid</span>
                </div>
                <div className={styles.contactItem}>
                  <MdAccessTime className={styles.contactIcon}/>
                  <span>Atención 24/7</span>
                </div>
              </div>
              
              <div className={styles.newsletterContainer}>
                <h3>Boletín Informativo</h3>
                <form className={styles.newsletterForm}>
                  <input type="email" placeholder="Tu correo electrónico" required />
                  <button type="submit">Suscribirse</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Footer bottom */}
      <div className={styles.footerBottom}>
        <div className={styles.container}>
          <div className={styles.bottomContent}>
            <p className={styles.copyright}>© {currentYear} VitalNest - Todos los derechos reservados</p>
            <div className={styles.bottomLinks}>
              <Link href="/privacidad">Política de Privacidad</Link>
              <Link href="/terminos">Términos de Uso</Link>
              <Link href="/cookies">Política de Cookies</Link>
              <Link href="/accesibilidad">Accesibilidad</Link>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
