// frontend/angular/src/app/shared/components/layout/header/header.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { TokenService } from '../../../../core/services/token/token.service';
import { UserService } from '../../../../core/services/auth/user.service';
import { SHARED_ROUTES } from '../../../../core/constants/shared.routes';

@Component({
    selector: 'app-header',
    standalone: true,
    imports: [RouterModule, CommonModule],
    templateUrl: './header.component.html',
    styleUrls: ['./header.component.scss']
})
export class HeaderComponent {
    menuOpen = false;
    routes = SHARED_ROUTES;
    
    constructor(
        public tokenService: TokenService,
        private userService: UserService,
    ) {}
    
    toggleMenu() {
        this.menuOpen = !this.menuOpen;
    }

    logout() {
        this.userService.logout();
        this.tokenService.clearAll();
        window.location.href = this.routes.NEXT.HOME;
    }
}

// import { Component } from '@angular/core';
// import { RouterModule } from '@angular/router';

// @Component({
//     selector: 'app-header',
//     standalone: true,
//     imports: [RouterModule],
//     templateUrl: './header.component.html',
//     styleUrls: ['./header.component.scss']
// })
// export class HeaderComponent {
//     menuOpen = false;
    
//     toggleMenu() {
//         this.menuOpen = !this.menuOpen;
//     }
// }
<header class="header">
    <div class="container">
        <div class="logo">
            <a [href]="routes.NEXT.HOME">
                <img src="/Logo_VitalNest.png" alt="VitalNest Logo" />
            </a>
        </div>
        <button class="hamburger" (click)="toggleMenu()" aria-label="Toggle menu">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </button>
        <nav class="nav" [class.navOpen]="menuOpen">
            <ul class="navList">
                <li class="navItem">
                    <a [href]="routes.NEXT.HOME" class="navLink">Página Principal</a>
                </li>
                <li class="navItem">
                    <a [href]="routes.NEXT.SHOP + '?activity_type='" class="navLink">Actividades</a>
                </li>
                <li class="navItem">
                    <a [href]="routes.NEXT.MEALS + '?type_meal=1'" class="navLink">Menús</a>
                </li>
                <li class="navItem" *ngIf="!tokenService.isAuthenticated()">
                    <a [routerLink]="routes.ANGULAR.AUTH.LOGIN" class="navLink">Login</a>
                </li>
                <li class="navItem" *ngIf="tokenService.isAuthenticated()">
                    <a (click)="logout()" class="navLink">Logout</a>
                </li>
            </ul>
        </nav>
    </div>
</header>

<!-- <header class="header">
    <div class="container">
        <div class="logo">
            <a routerLink="/home">
                <img src="/Logo_VitalNest.png" alt="VitalNest Logo" />
            </a>
        </div>
        <button class="hamburger" (click)="toggleMenu()" aria-label="Toggle menu">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </button>
        <nav class="nav" [class.navOpen]="menuOpen">
            <ul class="navList">
                <li class="navItem">
                    <a href="http://localhost:3000/" class="navLink">Página Principal</a>
                </li>
                <li class="navItem">
                    <a href="http://localhost:3000/shop?activity_type=" class="navLink">Actividades</a>
                </li>
                <li class="navItem">
                    <a href="http://localhost:3000/meals?type_meal=1" class="navLink">Menús</a>
                </li>
            </ul>
        </nav>
    </div>
</header>
 -->

// fullstack/next/src/components/layout/Header.tsx
'use client';

import Link from 'next/link';
import { useState } from 'react';
import styles from '../../styles/layout/Header.module.css';
import { SHARED_ROUTES } from '@/store/Constants';
import { isAuthenticated, logout } from '../../utils/auth';

const Header: React.FC = () => {
  const [menuOpen, setMenuOpen] = useState(false);

  const toggleMenu = () => {
    setMenuOpen(!menuOpen);
  };

  return (
    <header className={styles.header}>
      <div className={styles.container}>
        <div className={styles.logo}>
          <Link href={SHARED_ROUTES.NEXT.HOME}>
            <img src="/Logo_VitalNest.png" alt="VitalNest Logo" />
          </Link>
        </div>
        <button className={styles.hamburger} onClick={toggleMenu} aria-label="Toggle menu">
          <span className={styles.bar}></span>
          <span className={styles.bar}></span>
          <span className={styles.bar}></span>
        </button>
        <nav className={`${styles.nav} ${menuOpen ? styles.navOpen : ''}`}>
          <ul className={styles.navList}>
            <li className={styles.navItem}>
              <Link href={SHARED_ROUTES.NEXT.HOME} className={styles.navLink}>
                Página Principal
              </Link>
            </li>
            <li className={styles.navItem}>
              <Link href={`${SHARED_ROUTES.NEXT.SHOP}?activity_type=1`} className={styles.navLink}>
                Actividades
              </Link>
            </li>
            <li className={styles.navItem}>
              <Link href={`${SHARED_ROUTES.NEXT.MEALS}?type_meal=1`} className={styles.navLink}>
                Menús
              </Link>
            </li>
            {!isAuthenticated() ? (
                <li className={styles.navItem}>
                  <a href={SHARED_ROUTES.ANGULAR.AUTH.LOGIN} className={`${styles.navLink} ${styles.authButton}`}>
                    Login
                  </a>
                </li>
              ) : (
                <li className={styles.navItem}>
                  <button onClick={logout} className={styles.navLink}>
                    Logout
                  </button>
                </li>
            )}
          </ul>
        </nav>
      </div>
    </header>
  );
};

export default Header;



// 'use client';

// import Link from 'next/link';
// import { useState } from 'react';
// import styles from '../../styles/layout/Header.module.css';

// const Header: React.FC = () => {
//   const [menuOpen, setMenuOpen] = useState(false);
  

//   const toggleMenu = () => {
//     setMenuOpen(!menuOpen);
//   };

//   return (
//     <header className={styles.header}>
//       <div className={styles.container}>
//         <div className={styles.logo}>
//           <Link href="/home">
//             <img src="/Logo_VitalNest.png" alt="VitalNest Logo" />
//           </Link>
//         </div>
//         <button className={styles.hamburger} onClick={toggleMenu} aria-label="Toggle menu">
//           <span className={styles.bar}></span>
//           <span className={styles.bar}></span>
//           <span className={styles.bar}></span>
//         </button>
//         <nav className={`${styles.nav} ${menuOpen ? styles.navOpen : ''}`}>
//           <ul className={styles.navList}>
//             <li className={styles.navItem}>
//               <Link href="/home" className={styles.navLink}>
//                 Página Principal
//               </Link>
//             </li>
//             <li className={styles.navItem}>
//               <Link href="/shop?activity_type=1" className={styles.navLink}>
//                 Actividades
//               </Link>
//             </li>
//             <li className={styles.navItem}>
//               <Link href="/meals?type_meal=1" className={styles.navLink}>
//                 Menús
//               </Link>
//             </li>
//           </ul>
//         </nav>
//       </div>
//     </header>
//   );
// };

// export default Header;
